### ISSUE TITLE
how does read_fsm get rid of partially failed write?

### ISSUE THREAD

**Issue by liuzhen** [project-fifo/fifo_dt#2]
Say we have A, B, C vnodes for a datum, with "n-w-r" set to 3-2-2, which should be a "typical".

Step1, write only succeeded at *A*, failed at B & C, reporting to uplevel as failed;
Step2, read request firstly reached to A & B,  should we return *A*'s view of data?

According to ft_obj's merge function, *A* gets returned to uplevel, but for Step1, the write already has been reported failed.

Any newly partial successful write predominates the result, no quorum or others gets in to ensure a consensus while reading.

**Comment by Licenser** [comment]
This is intended behaviuour

**Comment by liuzhen** [comment]
I start to guess there might be no such mechanism, while your quick response confirmed, thanks.
